name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install black isort flake8 flake8-bugbear pre-commit pytest pytest-cov

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q --maxfail=1 --disable-warnings
